//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatePickerControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatePickerControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap calendar {
            get {
                object obj = ResourceManager.GetObject("calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap calendar_disabled {
            get {
                object obj = ResourceManager.GetObject("calendar_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap divider {
            get {
                object obj = ResourceManager.GetObject("divider", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap drop1 {
            get {
                object obj = ResourceManager.GetObject("drop1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap drop2 {
            get {
                object obj = ResourceManager.GetObject("drop2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap left1 {
            get {
                object obj = ResourceManager.GetObject("left1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap left2 {
            get {
                object obj = ResourceManager.GetObject("left2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //  written	by Tan Ling	Wee	on 2 Dec 2001
        /////  last updated 10 Apr 2002
        /////  email :	fuushikaden@yahoo.com
        /////  Modified (very little) by Sai on 01/02/05
        /////  email :	sai_freelance@yahoo.com
        /////  Modified (for VS2005 and latest browsers) by S. Baer on 2007-08-31
        /////  email : bae1@sevitec.ch
        /////  Modified (bugfix) by S. Baer on 2008-05-29
        /////  email : bae1@sevitec.ch
        /////  Modified (more bugfix, VS2008, FF3, IE7) by S. Baer on 2009-04-22
        /////  email : &lt;find.out&gt;@sevitec.ch
        /////  Modified (date format strings fi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string popcalendar {
            get {
                return ResourceManager.GetString("popcalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Default attributes of table container for entire calendar */
        ///.table-style {
        ///	font-family: arial;
        ///	border-width: 1; 
        ///	border-style: solid; 
        ///	border-color: #a0a0a0; 
        ///	background-color: #ffffff;
        ///	font-family: arial; 
        ///	font-size: 11px;
        ///}
        ///
        ///.table-style td {
        ///	border-style: none;
        ///	border-width: 0px;
        ///	padding: 1px;
        ///}
        ///
        ////* Default attributes of DIV containing table container for entire calendar.
        /// * You probably don&apos;t want to alter this style.
        /// */
        ///.div-style {
        ///	z-index: 999;
        ///	position: absolut [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string popcalendar1 {
            get {
                return ResourceManager.GetString("popcalendar1", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap right1 {
            get {
                object obj = ResourceManager.GetObject("right1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap right2 {
            get {
                object obj = ResourceManager.GetObject("right2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
